/**
 * @file server/src/conversation/llmAdapter.js
 * @description Optional Provider-Agnostic LLM Rewriter Adapter.
 * Fully declared comparison system; disabled by default.
 * Provides response caching and graceful fallback so system remains 100% operational
 * when LLM is disabled or unconfigured.
 */

import { CONFIG } from '../config/index.js';

// In-memory cache for deterministic reproducibility and zero redundant API calls
const RESPONSE_CACHE = new Map();

/**
 * Rewrites a conversational query using an external LLM (or mock/cached fallback).
 *
 * @param {string} rawQuery - Current query
 * @param {Array<{ role: 'user' | 'assistant', content: string }>} conversationHistory - Prior turns
 * @param {Object} [options]
 * @param {boolean} [options.forceEnabled=false]
 * @returns {Promise<{ rewrittenQuery: string, source: 'llm_api' | 'llm_cache' | 'llm_disabled_fallback' }>}
 */
export async function rewriteWithLLM(rawQuery, conversationHistory = [], options = {}) {
  const isEnabled = options.forceEnabled ?? CONFIG.conversation.llm.enabled;

  if (!isEnabled) {
    // When disabled, return clean standalone query with declaration metadata
    return {
      rewrittenQuery: rawQuery,
      source: 'llm_disabled_fallback',
      declaredStatus: 'LLM Adapter is disabled (System running on pure IR algorithms).'
    };
  }

  const cacheKey = JSON.stringify({ rawQuery, conversationHistory });
  if (CONFIG.conversation.llm.cacheResponses && RESPONSE_CACHE.has(cacheKey)) {
    return {
      rewrittenQuery: RESPONSE_CACHE.get(cacheKey),
      source: 'llm_cache',
      declaredStatus: 'Served from in-memory response cache.'
    };
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.OPENAI_API_KEY;
  if (!apiKey) {
    // Fallback if toggled on but API key is absent
    const lastUserTurn = conversationHistory.filter(h => h.role === 'user').slice(-1)[0]?.content || '';
    const simulatedRewrite = lastUserTurn ? `${rawQuery} (${lastUserTurn})` : rawQuery;
    return {
      rewrittenQuery: simulatedRewrite,
      source: 'llm_disabled_fallback',
      declaredStatus: 'API key not configured; pure IR fallback employed.'
    };
  }

  // Provider-agnostic call (e.g. Gemini / generic endpoint)
  try {
    const prompt = `Rewrite this conversational search query into a standalone, unambiguous search query based on conversation history.\nHistory: ${JSON.stringify(conversationHistory)}\nQuery: "${rawQuery}"\nStandalone query:`;
    
    // Example generic request (standard OpenAI/Gemini compliant payload)
    const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }]
      }),
      signal: AbortSignal.timeout(4000)
    });

    if (!res.ok) {
      throw new Error(`LLM API returned status ${res.status}`);
    }

    const data = await res.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
    const rewrittenQuery = candidateText ? candidateText.replace(/^"|"$/g, '') : rawQuery;

    if (CONFIG.conversation.llm.cacheResponses) {
      RESPONSE_CACHE.set(cacheKey, rewrittenQuery);
    }

    return {
      rewrittenQuery,
      source: 'llm_api',
      declaredStatus: 'Generated by declared LLM adapter.'
    };
  } catch (err) {
    // Graceful error fallback
    return {
      rewrittenQuery: rawQuery,
      source: 'llm_disabled_fallback',
      declaredStatus: `LLM API call failed (${err.message}); fallen back to pure IR.`
    };
  }
}
